apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: ./app.yaml
    repoURL: https://github.com/Nerogen/chart_nginx_argocd.git
    targetRevision: master
    helm:
      valueFiles:
        - chart/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true